version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.21
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 9411:9411
      - 14250:14250
      - 14268:14268
      - 16686:16686
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
