// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: sloweater-svc.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetImageBuildStatusResponse_ImageBuildStatus int32

const (
	GetImageBuildStatusResponse_UNKNOWN_STATUS GetImageBuildStatusResponse_ImageBuildStatus = 0
	GetImageBuildStatusResponse_ERROR          GetImageBuildStatusResponse_ImageBuildStatus = 1
	GetImageBuildStatusResponse_COMPLETED      GetImageBuildStatusResponse_ImageBuildStatus = 2
	GetImageBuildStatusResponse_LOADING        GetImageBuildStatusResponse_ImageBuildStatus = 3
)

// Enum value maps for GetImageBuildStatusResponse_ImageBuildStatus.
var (
	GetImageBuildStatusResponse_ImageBuildStatus_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "ERROR",
		2: "COMPLETED",
		3: "LOADING",
	}
	GetImageBuildStatusResponse_ImageBuildStatus_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"ERROR":          1,
		"COMPLETED":      2,
		"LOADING":        3,
	}
)

func (x GetImageBuildStatusResponse_ImageBuildStatus) Enum() *GetImageBuildStatusResponse_ImageBuildStatus {
	p := new(GetImageBuildStatusResponse_ImageBuildStatus)
	*p = x
	return p
}

func (x GetImageBuildStatusResponse_ImageBuildStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetImageBuildStatusResponse_ImageBuildStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sloweater_svc_proto_enumTypes[0].Descriptor()
}

func (GetImageBuildStatusResponse_ImageBuildStatus) Type() protoreflect.EnumType {
	return &file_sloweater_svc_proto_enumTypes[0]
}

func (x GetImageBuildStatusResponse_ImageBuildStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetImageBuildStatusResponse_ImageBuildStatus.Descriptor instead.
func (GetImageBuildStatusResponse_ImageBuildStatus) EnumDescriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{5, 0}
}

type GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps int32

const (
	GetImageBuildStatusResponse_BuildStepStatus_UNKNOWN_STEP GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps = 0
	GetImageBuildStatusResponse_BuildStepStatus_CLONE        GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps = 1
	GetImageBuildStatusResponse_BuildStepStatus_BUILD        GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps = 2
	GetImageBuildStatusResponse_BuildStepStatus_PUSH         GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps = 3
)

// Enum value maps for GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps.
var (
	GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps_name = map[int32]string{
		0: "UNKNOWN_STEP",
		1: "CLONE",
		2: "BUILD",
		3: "PUSH",
	}
	GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps_value = map[string]int32{
		"UNKNOWN_STEP": 0,
		"CLONE":        1,
		"BUILD":        2,
		"PUSH":         3,
	}
)

func (x GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps) Enum() *GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps {
	p := new(GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps)
	*p = x
	return p
}

func (x GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps) Descriptor() protoreflect.EnumDescriptor {
	return file_sloweater_svc_proto_enumTypes[1].Descriptor()
}

func (GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps) Type() protoreflect.EnumType {
	return &file_sloweater_svc_proto_enumTypes[1]
}

func (x GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps.Descriptor instead.
func (GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps) EnumDescriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{5, 0, 0}
}

type ScheduleImageBuildRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkloadId string `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	GitRepoUrl string `protobuf:"bytes,2,opt,name=git_repo_url,json=gitRepoUrl,proto3" json:"git_repo_url,omitempty"`
}

func (x *ScheduleImageBuildRequest) Reset() {
	*x = ScheduleImageBuildRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sloweater_svc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleImageBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleImageBuildRequest) ProtoMessage() {}

func (x *ScheduleImageBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sloweater_svc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleImageBuildRequest.ProtoReflect.Descriptor instead.
func (*ScheduleImageBuildRequest) Descriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleImageBuildRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *ScheduleImageBuildRequest) GetGitRepoUrl() string {
	if x != nil {
		return x.GitRepoUrl
	}
	return ""
}

type ScheduleImageBuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *ScheduleImageBuildResponse) Reset() {
	*x = ScheduleImageBuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sloweater_svc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleImageBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleImageBuildResponse) ProtoMessage() {}

func (x *ScheduleImageBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sloweater_svc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleImageBuildResponse.ProtoReflect.Descriptor instead.
func (*ScheduleImageBuildResponse) Descriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{1}
}

func (x *ScheduleImageBuildResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type ScheduleWorkloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScheduleWorkloadRequest) Reset() {
	*x = ScheduleWorkloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sloweater_svc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleWorkloadRequest) ProtoMessage() {}

func (x *ScheduleWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sloweater_svc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleWorkloadRequest.ProtoReflect.Descriptor instead.
func (*ScheduleWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{2}
}

type ScheduleWorkloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScheduleWorkloadResponse) Reset() {
	*x = ScheduleWorkloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sloweater_svc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleWorkloadResponse) ProtoMessage() {}

func (x *ScheduleWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sloweater_svc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleWorkloadResponse.ProtoReflect.Descriptor instead.
func (*ScheduleWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{3}
}

type GetImageBuildStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *GetImageBuildStatusRequest) Reset() {
	*x = GetImageBuildStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sloweater_svc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageBuildStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageBuildStatusRequest) ProtoMessage() {}

func (x *GetImageBuildStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sloweater_svc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageBuildStatusRequest.ProtoReflect.Descriptor instead.
func (*GetImageBuildStatusRequest) Descriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{4}
}

func (x *GetImageBuildStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetImageBuildStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status GetImageBuildStatusResponse_ImageBuildStatus   `protobuf:"varint,1,opt,name=status,proto3,enum=pb.GetImageBuildStatusResponse_ImageBuildStatus" json:"status,omitempty"`
	Steps  []*GetImageBuildStatusResponse_BuildStepStatus `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *GetImageBuildStatusResponse) Reset() {
	*x = GetImageBuildStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sloweater_svc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageBuildStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageBuildStatusResponse) ProtoMessage() {}

func (x *GetImageBuildStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sloweater_svc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageBuildStatusResponse.ProtoReflect.Descriptor instead.
func (*GetImageBuildStatusResponse) Descriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{5}
}

func (x *GetImageBuildStatusResponse) GetStatus() GetImageBuildStatusResponse_ImageBuildStatus {
	if x != nil {
		return x.Status
	}
	return GetImageBuildStatusResponse_UNKNOWN_STATUS
}

func (x *GetImageBuildStatusResponse) GetSteps() []*GetImageBuildStatusResponse_BuildStepStatus {
	if x != nil {
		return x.Steps
	}
	return nil
}

type GetWorkloadStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *GetWorkloadStatusRequest) Reset() {
	*x = GetWorkloadStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sloweater_svc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkloadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadStatusRequest) ProtoMessage() {}

func (x *GetWorkloadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sloweater_svc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadStatusRequest) Descriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkloadStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetWorkloadStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetWorkloadStatusResponse) Reset() {
	*x = GetWorkloadStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sloweater_svc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkloadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadStatusResponse) ProtoMessage() {}

func (x *GetWorkloadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sloweater_svc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadStatusResponse) Descriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{7}
}

type GetImageBuildStatusResponse_BuildStepStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step  GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps `protobuf:"varint,1,opt,name=step,proto3,enum=pb.GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps" json:"step,omitempty"`
	Error string                                                      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetImageBuildStatusResponse_BuildStepStatus) Reset() {
	*x = GetImageBuildStatusResponse_BuildStepStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sloweater_svc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageBuildStatusResponse_BuildStepStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageBuildStatusResponse_BuildStepStatus) ProtoMessage() {}

func (x *GetImageBuildStatusResponse_BuildStepStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sloweater_svc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageBuildStatusResponse_BuildStepStatus.ProtoReflect.Descriptor instead.
func (*GetImageBuildStatusResponse_BuildStepStatus) Descriptor() ([]byte, []int) {
	return file_sloweater_svc_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetImageBuildStatusResponse_BuildStepStatus) GetStep() GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps {
	if x != nil {
		return x.Step
	}
	return GetImageBuildStatusResponse_BuildStepStatus_UNKNOWN_STEP
}

func (x *GetImageBuildStatusResponse_BuildStepStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_sloweater_svc_proto protoreflect.FileDescriptor

var file_sloweater_svc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x6c, 0x6f, 0x77, 0x65, 0x61, 0x74, 0x65, 0x72, 0x2d, 0x73, 0x76, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x5e, 0x0a, 0x19, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72,
	0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x69, 0x74, 0x5f, 0x72,
	0x65, 0x70, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67,
	0x69, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x55, 0x72, 0x6c, 0x22, 0x33, 0x0a, 0x1a, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x19,
	0x0a, 0x17, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0xc1, 0x03, 0x0a, 0x1b, 0x47,
	0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x45, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x65, 0x70, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x1a, 0xc1, 0x01, 0x0a, 0x0f,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x65, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x53, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3f, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x65, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x65, 0x70, 0x73, 0x52, 0x04,
	0x73, 0x74, 0x65, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x43, 0x0a, 0x0f, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12, 0x10, 0x0a,
	0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x54, 0x45, 0x50, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x55,
	0x49, 0x4c, 0x44, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x55, 0x53, 0x48, 0x10, 0x03, 0x22,
	0x4d, 0x0a, 0x10, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x4f, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x22, 0x31,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f,
	0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49,
	0x64, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe1,
	0x02, 0x0a, 0x09, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x12, 0x55, 0x0a, 0x12,
	0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x10, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62,
	0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sloweater_svc_proto_rawDescOnce sync.Once
	file_sloweater_svc_proto_rawDescData = file_sloweater_svc_proto_rawDesc
)

func file_sloweater_svc_proto_rawDescGZIP() []byte {
	file_sloweater_svc_proto_rawDescOnce.Do(func() {
		file_sloweater_svc_proto_rawDescData = protoimpl.X.CompressGZIP(file_sloweater_svc_proto_rawDescData)
	})
	return file_sloweater_svc_proto_rawDescData
}

var file_sloweater_svc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sloweater_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sloweater_svc_proto_goTypes = []interface{}{
	(GetImageBuildStatusResponse_ImageBuildStatus)(0),                // 0: pb.GetImageBuildStatusResponse.ImageBuildStatus
	(GetImageBuildStatusResponse_BuildStepStatus_ImageBuildSteps)(0), // 1: pb.GetImageBuildStatusResponse.BuildStepStatus.ImageBuildSteps
	(*ScheduleImageBuildRequest)(nil),                                // 2: pb.ScheduleImageBuildRequest
	(*ScheduleImageBuildResponse)(nil),                               // 3: pb.ScheduleImageBuildResponse
	(*ScheduleWorkloadRequest)(nil),                                  // 4: pb.ScheduleWorkloadRequest
	(*ScheduleWorkloadResponse)(nil),                                 // 5: pb.ScheduleWorkloadResponse
	(*GetImageBuildStatusRequest)(nil),                               // 6: pb.GetImageBuildStatusRequest
	(*GetImageBuildStatusResponse)(nil),                              // 7: pb.GetImageBuildStatusResponse
	(*GetWorkloadStatusRequest)(nil),                                 // 8: pb.GetWorkloadStatusRequest
	(*GetWorkloadStatusResponse)(nil),                                // 9: pb.GetWorkloadStatusResponse
	(*GetImageBuildStatusResponse_BuildStepStatus)(nil),              // 10: pb.GetImageBuildStatusResponse.BuildStepStatus
}
var file_sloweater_svc_proto_depIdxs = []int32{
	0,  // 0: pb.GetImageBuildStatusResponse.status:type_name -> pb.GetImageBuildStatusResponse.ImageBuildStatus
	10, // 1: pb.GetImageBuildStatusResponse.steps:type_name -> pb.GetImageBuildStatusResponse.BuildStepStatus
	1,  // 2: pb.GetImageBuildStatusResponse.BuildStepStatus.step:type_name -> pb.GetImageBuildStatusResponse.BuildStepStatus.ImageBuildSteps
	2,  // 3: pb.Scheduler.ScheduleImageBuild:input_type -> pb.ScheduleImageBuildRequest
	4,  // 4: pb.Scheduler.ScheduleWorkload:input_type -> pb.ScheduleWorkloadRequest
	6,  // 5: pb.Scheduler.GetImageBuildStatus:input_type -> pb.GetImageBuildStatusRequest
	8,  // 6: pb.Scheduler.GetWorkloadStatus:input_type -> pb.GetWorkloadStatusRequest
	3,  // 7: pb.Scheduler.ScheduleImageBuild:output_type -> pb.ScheduleImageBuildResponse
	5,  // 8: pb.Scheduler.ScheduleWorkload:output_type -> pb.ScheduleWorkloadResponse
	7,  // 9: pb.Scheduler.GetImageBuildStatus:output_type -> pb.GetImageBuildStatusResponse
	9,  // 10: pb.Scheduler.GetWorkloadStatus:output_type -> pb.GetWorkloadStatusResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_sloweater_svc_proto_init() }
func file_sloweater_svc_proto_init() {
	if File_sloweater_svc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sloweater_svc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleImageBuildRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sloweater_svc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleImageBuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sloweater_svc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleWorkloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sloweater_svc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleWorkloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sloweater_svc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageBuildStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sloweater_svc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageBuildStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sloweater_svc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkloadStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sloweater_svc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkloadStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sloweater_svc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetImageBuildStatusResponse_BuildStepStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sloweater_svc_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sloweater_svc_proto_goTypes,
		DependencyIndexes: file_sloweater_svc_proto_depIdxs,
		EnumInfos:         file_sloweater_svc_proto_enumTypes,
		MessageInfos:      file_sloweater_svc_proto_msgTypes,
	}.Build()
	File_sloweater_svc_proto = out.File
	file_sloweater_svc_proto_rawDesc = nil
	file_sloweater_svc_proto_goTypes = nil
	file_sloweater_svc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulerClient interface {
	ScheduleImageBuild(ctx context.Context, in *ScheduleImageBuildRequest, opts ...grpc.CallOption) (*ScheduleImageBuildResponse, error)
	ScheduleWorkload(ctx context.Context, in *ScheduleWorkloadRequest, opts ...grpc.CallOption) (*ScheduleWorkloadResponse, error)
	GetImageBuildStatus(ctx context.Context, in *GetImageBuildStatusRequest, opts ...grpc.CallOption) (*GetImageBuildStatusResponse, error)
	GetWorkloadStatus(ctx context.Context, in *GetWorkloadStatusRequest, opts ...grpc.CallOption) (*GetWorkloadStatusResponse, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) ScheduleImageBuild(ctx context.Context, in *ScheduleImageBuildRequest, opts ...grpc.CallOption) (*ScheduleImageBuildResponse, error) {
	out := new(ScheduleImageBuildResponse)
	err := c.cc.Invoke(ctx, "/pb.Scheduler/ScheduleImageBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ScheduleWorkload(ctx context.Context, in *ScheduleWorkloadRequest, opts ...grpc.CallOption) (*ScheduleWorkloadResponse, error) {
	out := new(ScheduleWorkloadResponse)
	err := c.cc.Invoke(ctx, "/pb.Scheduler/ScheduleWorkload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetImageBuildStatus(ctx context.Context, in *GetImageBuildStatusRequest, opts ...grpc.CallOption) (*GetImageBuildStatusResponse, error) {
	out := new(GetImageBuildStatusResponse)
	err := c.cc.Invoke(ctx, "/pb.Scheduler/GetImageBuildStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetWorkloadStatus(ctx context.Context, in *GetWorkloadStatusRequest, opts ...grpc.CallOption) (*GetWorkloadStatusResponse, error) {
	out := new(GetWorkloadStatusResponse)
	err := c.cc.Invoke(ctx, "/pb.Scheduler/GetWorkloadStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
type SchedulerServer interface {
	ScheduleImageBuild(context.Context, *ScheduleImageBuildRequest) (*ScheduleImageBuildResponse, error)
	ScheduleWorkload(context.Context, *ScheduleWorkloadRequest) (*ScheduleWorkloadResponse, error)
	GetImageBuildStatus(context.Context, *GetImageBuildStatusRequest) (*GetImageBuildStatusResponse, error)
	GetWorkloadStatus(context.Context, *GetWorkloadStatusRequest) (*GetWorkloadStatusResponse, error)
}

// UnimplementedSchedulerServer can be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (*UnimplementedSchedulerServer) ScheduleImageBuild(context.Context, *ScheduleImageBuildRequest) (*ScheduleImageBuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleImageBuild not implemented")
}
func (*UnimplementedSchedulerServer) ScheduleWorkload(context.Context, *ScheduleWorkloadRequest) (*ScheduleWorkloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleWorkload not implemented")
}
func (*UnimplementedSchedulerServer) GetImageBuildStatus(context.Context, *GetImageBuildStatusRequest) (*GetImageBuildStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImageBuildStatus not implemented")
}
func (*UnimplementedSchedulerServer) GetWorkloadStatus(context.Context, *GetWorkloadStatusRequest) (*GetWorkloadStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkloadStatus not implemented")
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_ScheduleImageBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleImageBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ScheduleImageBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Scheduler/ScheduleImageBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ScheduleImageBuild(ctx, req.(*ScheduleImageBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ScheduleWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ScheduleWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Scheduler/ScheduleWorkload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ScheduleWorkload(ctx, req.(*ScheduleWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetImageBuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageBuildStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetImageBuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Scheduler/GetImageBuildStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetImageBuildStatus(ctx, req.(*GetImageBuildStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetWorkloadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetWorkloadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Scheduler/GetWorkloadStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetWorkloadStatus(ctx, req.(*GetWorkloadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleImageBuild",
			Handler:    _Scheduler_ScheduleImageBuild_Handler,
		},
		{
			MethodName: "ScheduleWorkload",
			Handler:    _Scheduler_ScheduleWorkload_Handler,
		},
		{
			MethodName: "GetImageBuildStatus",
			Handler:    _Scheduler_GetImageBuildStatus_Handler,
		},
		{
			MethodName: "GetWorkloadStatus",
			Handler:    _Scheduler_GetWorkloadStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sloweater-svc.proto",
}
